---
deployment:
 tasks:
 - export DEPLOYPATH = /home/zoidhbzhj292/ourhub/flaskblog
 - /bin/cp __init__.py $DEPLOYPATH
 - /bin/cp forms.py $DEPLOYPATH
 - /bin/cp models.py $DEPLOYPATH
 - /bin/cp routes.py $DEPLOYPATH
 - /bin/cp site.db $DEPLOYPATH
 - /bin/cp -R static $DEPLOYPATH
 - /bin/cp -R templates $DEPLOYPATH

